name: "uni-meter"
description: "A universal electrical meter converter"
version: "1.1.3"
slug: "uni_meter"
url: "https://github.com/sdeigm/uni-meter"
panel_icon: "mdi:barometer"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
startup: services
homeassistant_api: true
hassio_api: true
hassio_role: homeassistant
host_network: true
ports:
  80/tcp: 80
  1010/udp: 1010
map:
  - type: addon_config
    read_only: true
options:
  custom_config: "uni-meter.conf"
schema:
  custom_config: str?