services:
  uni-meter:
    image: sdeigm/uni-meter:latest
    container_name: uni-meter
    network_mode: host
    restart: unless-stopped
    ports:
      - 80:80/tcp
      - 1010:1010/udp
      - 5353:5353/udp
    expose:
      - 80/tcp
      - 1010/udp
      - 5353/udp
    volumes:
      - ./uni-meter.conf:/etc/uni-meter.conf
      - ./logback.xml:/opt/uni-meter/config/logback.xml
      - ./shellypro3em.http.tcp.service:/etc/avahi/services/shellypro3em.http.tcp.service
      - ./shellypro3em.shelly.tcp.service:/etc/avahi/services/shellypro3em.shelly.tcp.service
